<?php
/**
 * Megamenu extends Topmenu
 *
 * @see \Magento\Theme\Block\Html\Topmenu
 */
?>

<?php $columnsLimit = $block->getColumnsLimit() ? : 0; ?>
<?php $_menu2 = $block->getHtml2('level-top', 'submenu', $columnsLimit) ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>
<?php if ($block->allowExtension()): ?>
    <?php
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();    
        $helper = $objectManager->get('Jnext\Megamenu\Helper\Data');
        $catLabel1Bgcolor = $helper->getCatLabel1Bgolor();
        $catLabel2Bgcolor = $helper->getCatLabel2Bgolor();
        $catLabel3Bgcolor = $helper->getCatLabel3Bgolor();
        $catLabel4Bgcolor = $helper->getCatLabel4Bgolor();
    ?>
    <style type="text/css">
        .megamenu .category_label1 .cat-label:before {border-top-color: <?=$catLabel1Bgcolor?>; }
        .megamenu .category_label1 .cat-label {background: <?=$catLabel1Bgcolor?> none repeat scroll 0 0; }
        .megamenu .category_label2 .cat-label:before {border-top-color: <?=$catLabel2Bgcolor?>; }
        .megamenu .category_label2 .cat-label {background: <?=$catLabel2Bgcolor?> none repeat scroll 0 0; }
        .megamenu .category_label3 .cat-label:before {border-top-color: <?=$catLabel3Bgcolor?>; }
        .megamenu .category_label3 .cat-label {background: <?=$catLabel3Bgcolor?> none repeat scroll 0 0; }
        .megamenu .category_label4 .cat-label:before {border-top-color: <?=$catLabel4Bgcolor?>; }
        .megamenu .category_label4 .cat-label {background: <?=$catLabel4Bgcolor?> none repeat scroll 0 0; }
    </style>
    <script>
        require([
            'jquery',
            'jnextmodernizr'
        ], function ($)
        {
            //$('.menu > ul > li:has( > ul)').addClass('menu-dropdown-icon');
            //Checks if li has sub (ul) and adds class for toggle icon - just an UI

            //$('.menu > ul > li > ul:not(:has(ul))').addClass('normal-sub');
            //Checks if drodown menu's li elements have anothere level (ul), if not the dropdown is shown as regular dropdown, not a mega menu (thanks Luka Kladaric)

            //$(".menu > ul").before("<a href=\"#\" class=\"menu-mobile\">Navigation</a>");

            //Adds menu-mobile class (for mobile toggle menu) before the normal menu
            //Mobile menu is hidden if width is more then 959px, but normal menu is displayed
            //Normal menu is hidden if width is below 959px, and jquery adds mobile menu
            //Done this way so it can be used with wordpress without any trouble

            /*$(".menu > ul > li").hover(function (e) {
                if ($(window).width() > 943) {
                    $(this).children("ul").stop(true, false).fadeToggle(150);
                    e.preventDefault();
                }
            });*/
            //If width is more than 943px dropdowns are displayed on hover

            /*$(".menu > ul > li").click(function () {
                if ($(window).width() <= 943) {
                    $(this).children("ul").fadeToggle(150);
                }
            });*/
            //If width is less or equal to 943px dropdowns are displayed on click (thanks Aman Jain from stackoverflow)

            /*$(".menu-mobile").click(function (e) {
                $(".menu > ul").toggleClass('show-on-mobile');
                e.preventDefault();
            });*/
        });
    </script>
    <nav class="navigation" role="navigation" >
        <div class="megamenu">
            <?php echo $_menu2; ?>
        </div>
        <ul id="dm" data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
            <?php /* @escapeNotVerified */ echo $_menu; ?>
        </ul>
    </nav>
<?php else : ?>
    <nav class="navigation" role="navigation">
        <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
            <?php /* @escapeNotVerified */ echo $_menu; ?>
        </ul>
    </nav>
<?php endif; ?>